# Generated by Django 4.2.3 on 2023-07-24 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_producer_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movie_app.genre'),
        ),
    ]
